# Generated by Django 5.0.7 on 2025-04-05 00:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apisapp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
